### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by DantheCodingGui** [Comcast/resourceprovider2#11]
Hi,

Just checked my unit tests and they seem to be failing due to resource provider.

I'm only generating StringProvider and it seems that the plugin generates a ResourceProviderTestUtils.kt file that references all the provider classes, whether you've said to generate them or not.

As those provider classes haven't been generated it crashes my tests.

Thanks

**Comment by dapp** [comment]
Fixed in https://github.com/Comcast/resourceprovider2/releases/tag/1.4.1
