### ISSUE TITLE
Continued failing tests

### ISSUE THREAD

**Issue by DantheCodingGui** [Comcast/resourceprovider2#13]
That previous test fix looks to work fine, it's just trying to generate what I've set in testutils now.

Getting another error now, Looks like the `testutils` dir and (at least in my case) `StringProviderAnswer` aren't being generated at all so it still fails building the tests.

Don't know if this is another Windows command thing but I'm not getting any obvious 'command not found' errors in my build output.

**Comment by dapp** [comment]
Whoops, yes you still need the testutils lib from rp1.  Those answers aren't generated, they're static.  

Checkout https://github.com/Comcast/resourceprovider-utils#setup for the setup.

I'll add it to the readme of this project as well.

**Comment by dapp** [comment]
Added a snippet to the readme, to explicitly reference the setup of test  utilities

https://github.com/Comcast/resourceprovider2/commit/75d1d39e74271a99e8259af46e966fffb3f2e368
