### ISSUE TITLE
Support for plural strings

### ISSUE THREAD

**Issue by DantheCodingGui** [Comcast/resourceprovider2#14]
Hi,

Just noticed that as of now stringsProvider doesn't generate plural/quantity strings. Don't know how difficult this would be to add but presumably would generate a getQuantityString call w/ a required param for quantity.

Something like this maybe:
```
  public String getExamplePlural(int quantity, Object... formatArgs) {
    return context.getResources().getQuantityString(R.plurals.example_plural, quantity, formatArgs);
  }
```

Thanks

**Comment by dapp** [comment]
@DantheCodingGui  ResourceProvider already supports plurals

The function name in StringProvider would be:

getExampleQuantityString

so you'd call resourceProvider.strings.getExampleQuantityString(quantity, formatArgs)

Please let me know if RP isn't generating your plurals.
