### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by DantheCodingGui** [Comcast/resourceprovider2#2]
Hi, I've finally got around to trying out the resource provider 2.0.

I tried porting it over based on the readme here and your medium article for my project and it didn't seem to be working, was getting this error:
 `Execution failed for task ':generateDevelopmentDebugResourceProvider'. A problem occurred starting process 'command 'unzip''`
( Don't know if it's because I'm using multiple build flavours? )

So I tried it in a completely new blank android project to see if that worked and the build succeeded but the ResourceProvider class wasn't getting generated at all.

I don't know if I'm just setting it up wrong but some guidance would be much appreciated. Even just a sample project with the new plugin working as intended would be helpful, so I have a point of reference to go from.

Thanks

**Comment by dapp** [comment]
What happens if you just go to the command line and type unzip?

If the unzip executable isn't in your path, RP will fail

**Comment by dapp** [comment]
There's a sample project here: https://github.com/Comcast/resourceprovider-utils

**Comment by DantheCodingGui** [comment]
Yeah it doesn't recognize the unzip command, is that an in-built windows command? 

If so do you know where abouts the executable is so I can add it to my path, googling hasn't helped me out much

**Comment by dapp** [comment]
ah whoops, I only tested on mac and linux.

**Comment by dapp** [comment]
Ok, I think I can swap the unzip command out for "jar xf"

Can you verify that the "jar" command works on windows?

**Comment by DantheCodingGui** [comment]
On it's own "jar" doesn't work, but "java -jar" does

**Comment by dapp** [comment]
can you try to find the jar exe?  outlined here: https://stackoverflow.com/a/8453600/502463

**Comment by DantheCodingGui** [comment]
Looked through it, looks like the jar exe's location depends on how you have the JDK setup.

With that post the JDK (and the jar exe) is part of the java install, but looking at my personal setup, it's using the embedded JDK/JRE with the jar exe at C:\Program Files\Android\Android Studio\jre\bin

I'm guessing the right place to look would be the same JDK location set in the Project Structure in Android Studio, but I have no idea if that's something you can access from a plugin.

I would say you could get the value of the JAVA_HOME env variable but looks like it isn't set if you're using the embedded jdk

**Comment by dapp** [comment]
I can switch the plugin to use the jar command, you'll just need to either find it and add it to your path, install the JDK, or create an alias for it.

**Comment by DantheCodingGui** [comment]
If that's the only solution to this then it'll have to do. 

Thanks for looking into this so quickly, much appreciated

**Comment by dapp** [comment]
@DantheCodingGui  can you please retest with version 1.3.1?  Again, you'll need to have the jar command on your system PATH, so you might have to install the JDK/JRE

**Comment by DantheCodingGui** [comment]
Good news, with jar added to the path I'm not getting any unzip errors.

Bad news, looks like it's failing on another command, 'bash' (I'm gonna guess that won't work on windows)

Don't know how many commands you're using, but if it's easier I have no problem testing all of them on my end if you send me a list

**Comment by dapp** [comment]
D'oh.  Thanks for being the guinnea pig for windows compatibility.  So windows actually *does* have a bash shell, you just have to turn it on.  You can try this?

https://www.laptopmag.com/articles/use-bash-shell-windows-10

**Comment by DantheCodingGui** [comment]
No Problem :)

Installed bash, command works in a windows cmd shell. I'm getting "Process 'command 'bash'' finished with non-zero exit value 127"

I will say though, even if we could get bash to work I'd appreciate it if it was a shorter term solution and would ask if you could look into any other potential ways of getting the plugin working. If I were the only developer on my project it would be one thing, but it's an enterprise app so not ideal with a team of developers.

**Comment by dapp** [comment]
I'd love to develop a solution for you, I just don't have access to a windows machine or vm.  I'm working on getting one setup. 

the bash command I'm using is to organize the expanded R file classes into a text file that I then use to generate the code.  the bash command is:

find ${rClassDir.absolutePath} -name '*.class' | xargs javap -p > rclass.txt

if you want to translate that into a windows shell command I can implement it for you.  I just have no way to test it.

**Comment by dapp** [comment]
@DantheCodingGui I think I have a fix for you.... can you confirm that the "javap" command works from your windows shell?

**Comment by DantheCodingGui** [comment]
@dapp Yep it does, same dir as jar.exe so already in my path

**Comment by dapp** [comment]
Awesome, I should have a fix for you by eod

**Comment by DantheCodingGui** [comment]
Sweet, I Look forward to it!

**Comment by dapp** [comment]
Just published v1.3.2, give it a shot and see if it works for you.  I still haven't been able to test on windows, but I eliminated the bash command, and it's tested and working for me on my mac.

**Comment by DantheCodingGui** [comment]
Success!!...kinda

With a blank project i'm getting Resource Provider generated, having some issues with my existing project so i'll have to do some digging. Also found a few other issues but i'll open them separately.
