### ISSUE TITLE
Id Provider ignores flag

### ISSUE THREAD

**Issue by DantheCodingGui** [Comcast/resourceprovider2#5]
Hi,

Got my plugin set up as follows

`
resourceprovider {
    packageName = <appId>
    generateIdProvider = false
    generateIntegerProvider = false
    generateDimenProvider = false
    generateColorProvider = false
    generateDrawableProvider = false
}
`

Since I only use resource provider for strings, but i'm getting IdProvider generated as well, and i'm guessing it's part of the reason why my project is building so slowly.

**Comment by dapp** [comment]
Fixed in https://github.com/Comcast/resourceprovider2/pull/9, available in v1.3.3
