### ISSUE TITLE
Library resource generation

### ISSUE THREAD

**Issue by DantheCodingGui** [Comcast/resourceprovider2#8]
Small optimisation thing if possible.

Resource provider seems to generate based off everything included in an application, including library resources.

Would it be possible to generate resources based on only your resources and not included libraries?

Would save a load of bloat from the generated files, and I doubt anyone will be accessing library resources with resource provider (and if they are, they probably shouldn't be)

**Comment by dapp** [comment]
Addressed in v1.4.0 https://github.com/Comcast/resourceprovider2/releases/tag/1.4.0
